baseURL = 'https://magley.github.io/'
languageCode = 'en-us'
title = "magley"

[params]
title = "magley"


[markup]
[markup.highlight]
style = 'onesenterprise'
linenos = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Files"
    url = "/files/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4